modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT license"

[[mods]]
    modId="trickiertrials"
    version="1.0"
    displayName="Trickier Trials"
    logoFile="pack.png"
    authors="Slimei"
    description="A completely new Trial Experience!"

[[dependencies.trickiertrials]]
    modId="forge"
    mandatory=false
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trickiertrials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"